CREATE TABLE IF NOT EXISTS ligas (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS times (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  campeonato_id INT NOT NULL,
  grupo VARCHAR(255) NOT NULL,
  brasao VARCHAR(512),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (nome, campeonato_id, grupo),
  FOREIGN KEY (campeonato_id) REFERENCES ligas(id) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partidas (
  id INT PRIMARY KEY AUTO_INCREMENT,
  campeonato_id INT NOT NULL,
  grupo VARCHAR(255) DEFAULT '',
  rodada INT DEFAULT 1,
  data_partida DATETIME DEFAULT CURRENT_TIMESTAMP,
  time_casa_id INT NOT NULL,
  time_fora_id INT NOT NULL,
  gols_casa INT DEFAULT 0,
  gols_fora INT DEFAULT 0,
  finalizada TINYINT DEFAULT 0,
  FOREIGN KEY (campeonato_id) REFERENCES ligas(id) ON DELETE CASCADE,
  FOREIGN KEY (time_casa_id) REFERENCES times(id) ON DELETE CASCADE,
  FOREIGN KEY (time_fora_id) REFERENCES times(id) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS videos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(255) DEFAULT '',
  link VARCHAR(255) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
