services:
  esportevale-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    container_name: esportevale-web
    networks:
      - app-network

networks:
  app-network:
